name: build and test

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: install dependencies
        run: yarn install

      - name: build
        run: yarn build

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: install dependencies
        run: yarn install

      - name: start server
        run: |
          yarn serve &
          sleep 10

      - name: run test script
        run: yarn test 
