name: "DAST Workflow"

on:
    push:
      branches:
        - '**'
    pull_request:
      branches: ["master"]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 使用 Node.js 16.x（任何小版本）

      - name: Install Dependencies
        run: |
          rm -f package-lock.json # 确保只使用 Yarn
          yarn install --frozen-lockfile

      - name: Start Vue.js Development Server
        run: |
          yarn serve &
        timeout-minutes: 5

      - name: Run OWASP ZAP Scan
        run: |
          docker pull zaproxy/zap-stable
          docker run -i zaproxy/zap-stable zap-baseline.py -t "http://localhost:8080/" -l PASS > zap_baseline_report.html || true

      - name: Archive DAST Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_baseline_report.html
