name: "sast-scan"

on:
    push:
      branches:
        - '**'
    pull_request:
      branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.2.0/dependency-check-7.2.0-release.zip
          unzip dependency-check-7.2.0-release.zip

      - name: Run scan with ODC
        run: |
          dependency-check/bin/dependency-check.sh --project "vue-project" --scan yarn.lock > ODC-report

      - name: Archive SAST Report
        uses: actions/upload-artifact@v3
        with:
          name: ODC-report
          path: |
            ./ODC-report
